server:
  host: 127.0.0.1
  port: 8180
  servlet:
    context-path: /job-manage

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: job-manage
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/dragon_job?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: dragon_job
    password: dragon_job
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
    jackson:
      time-zone: GMT+8
  mvc:
   static-path-pattern: /static/**
  resources:
   static-locations: classpath:/static/
### freemarker
  freemarker:
   templateLoaderPath: classpath:/templates/
   suffix: .ftl
   charset: UTF-8
   request-context-attribute: request
   settings.number_format: 0.##########
### xxl-job email
  mail:
   host: smtp.qq.com
   port: 25
   username: xxx@qq.com
   password: xxx
   properties:
    mail:
     smtp:
      auth: true
      starttls:
       enable: true
       required: true
### mybatis
mybatis:
 mapper-locations: classpath:/mybatis-mapper/*Mapper.xml


### xxl-job login
xxl:
 job:
  login:
   username: admin
   password: 123456

### xxl-job, access token
  accessToken:

### xxl-job, i18n (default empty as chinese, "en" as english)
  i18n:
